spring.application.name=agencia-java
agencia.id=${AGENCIA_ID:0}
agencia.offset=${OFFSET:22}

jwt.secret=uma-chave-bem-longa-e-aleatoria-com-pelo-menos-32-caracteres-para-ser-segura
jwt.expiracao-minutos=30

agencia.token-interno=segredo-compartilhado-entre-as-3-agencias-do-iceibank